# Generated by Django 4.2.27 on 2026-03-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
